server:
  port: 9003
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: manager-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      uri: ${CONFIG_SERVICE_URL:http://localhost:9001}
      fail-fast: false
      retry:
        max-attempts: 20
        max-interval: 10000
        initial-interval: 3000
        multiplier: 1.3
    stream:
      bindings:
        supplyAddress-out-0:
          destination: address-supplied
  data:
    mongodb:
      username: admin
      database: admin
      password: admin
      port: 27017
      host: hypercrawler-mongo
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    connection-timeout: 5s
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: hypercrawler

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:9000/eureka/}
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
