server:
  port: 9003
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: supplier-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      uri: ${CONFIG_SERVICE_URL:http://localhost:9001}
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 10000
        initial-interval: 3000
        multiplier: 1.3

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: hypercrawler

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8090/eureka/}
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}