apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  labels:
    app: supplier-service
spec:
  type: ClusterIP
  selector:
    app: supplier-service
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003