apiVersion: v1
kind: Service
metadata:
  name: manager-service
  labels:
    app: manager-service
spec:
  type: ClusterIP
  selector:
    app: manager-service
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003